# Generated by Django 6.1 on 2026-08-22 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("home_lat", models.FloatField(blank=True, null=True)),
                ("home_lng", models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=300)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=2)),
                ("zip_code", models.CharField(blank=True, max_length=10)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lng", models.FloatField(blank=True, null=True)),
                ("tank_size_gallons", models.PositiveIntegerField(blank=True, null=True)),
                ("system_type", models.CharField(blank=True, max_length=50)),
                ("pump_interval_months", models.PositiveIntegerField(default=36)),
                ("last_pumped", models.DateField(blank=True, null=True)),
                ("next_due", models.DateField(blank=True, db_index=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("route_day", models.DateField()),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("gallons", models.PositiveIntegerField(blank=True, null=True)),
                ("disposal_site", models.CharField(blank=True, max_length=200)),
                ("completion_notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.customer",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["route_day", "position", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization", "customer", "route_day"),
                        name="unique_customer_per_route_day",
                    )
                ],
            },
        ),
    ]
