# Generated by Django 6.1 on 2026-08-23 01:40

import django.db.models.deletion
from django.db import migrations, models

from core.models import _tank_identity_key


def backfill_tank_keys(apps, schema_editor):
    """Give pre-existing customers their parcel/address identity key."""
    customer = apps.get_model("core", "customer")
    for row in customer.objects.all():
        row.tank_key = _tank_identity_key(
            parcel_id=row.parcel_id,
            address=row.address,
            city=row.city,
            zip_code=row.zip_code,
        )
        row.save(update_fields=["tank_key"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="job",
            options={"ordering": ("route_day", "position", "pk")},
        ),
        migrations.AddField(
            model_name="customer",
            name="assessor_lot",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="customer",
            name="assessor_map",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="customer",
            name="parcel_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="customer",
            name="tank_key",
            field=models.CharField(blank=True, db_index=True, max_length=450),
        ),
        migrations.CreateModel(
            name="TankEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("event_date", models.DateField()),
                ("gallons", models.PositiveIntegerField(blank=True, null=True)),
                ("disposal_site", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("job_completion", "Job completion"),
                            ("manual_entry", "Manual entry"),
                            ("import_backfill", "Import backfill"),
                        ],
                        default="job_completion",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tank_events",
                        to="core.customer",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tank_events",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "ordering": ("-event_date", "-pk"),
                "indexes": [
                    models.Index(fields=["customer", "event_date"], name="tankevent_cust_date")
                ],
            },
        ),
        migrations.RunPython(backfill_tank_keys, migrations.RunPython.noop),
    ]
