# Generated by Django 6.1 on 2026-08-23 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_customer_options_alter_job_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Jurisdiction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("state", models.CharField(max_length=2)),
                ("town", models.CharField(blank=True, max_length=100)),
                ("county", models.CharField(blank=True, max_length=100)),
                ("filing_rule", models.CharField(max_length=120)),
                ("deadline_days", models.PositiveIntegerField(default=14)),
                ("form_variant", models.CharField(max_length=120)),
                ("effective_from", models.DateField()),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("change_log", models.TextField(blank=True)),
            ],
            options={
                "ordering": ("state", "town", "-effective_from"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("state", "town", "effective_from"),
                        name="unique_rule_per_scope_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("effective_to__isnull", True),
                            ("effective_to__gte", models.F("effective_from")),
                            _connector="OR",
                        ),
                        name="effective_window_sane",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="FilingReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("filed_on", models.DateField()),
                ("filed_by", models.CharField(max_length=120)),
                ("receipt_ref", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing_receipt",
                        to="core.job",
                    ),
                ),
                (
                    "jurisdiction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="core.jurisdiction",
                    ),
                ),
            ],
            options={
                "ordering": ("-filed_on", "-pk"),
            },
        ),
    ]
