# Generated by Django 6.1 on 2026-08-23 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_seed_ne_jurisdictions"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaseStudy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Customer-facing company name", max_length=200),
                ),
                ("location", models.CharField(blank=True, max_length=120)),
                ("trucks", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "quote",
                    models.TextField(help_text="The customer's words, verbatim once verified"),
                ),
                (
                    "outcome",
                    models.TextField(help_text="Hours saved, filings on time, route-sale value"),
                ),
                ("contact_name", models.CharField(blank=True, max_length=120)),
                ("is_callable", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=True)),
                ("sample", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="case_studies",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-is_callable", "title"),
            },
        ),
    ]
