# Generated by Django 6.1 on 2026-08-23 06:04

import core.billing_models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_seed_case_studies"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("number", models.CharField(max_length=16, unique=True)),
                (
                    "public_token",
                    models.CharField(
                        default=core.billing_models.make_token, max_length=64, unique=True
                    ),
                ),
                ("issued_on", models.DateField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("due", "Due"), ("paid", "Paid"), ("void", "Void")],
                        db_index=True,
                        default="due",
                        max_length=8,
                    ),
                ),
                ("lines", models.JSONField(default=list)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("paid_on", models.DateField(blank=True, null=True)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("card_link", "Card (online link)"),
                            ("check", "Check"),
                            ("cash", "Cash"),
                            ("ach", "ACH transfer"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "job",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoice",
                        to="core.job",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "ordering": ("-issued_on", "-pk"),
            },
        ),
        migrations.CreateModel(
            name="RateCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=Decimal("350.00"), max_digits=8),
                ),
                ("included_gallons", models.PositiveIntegerField(default=1000)),
                (
                    "overage_per_gallon",
                    models.DecimalField(decimal_places=2, default=Decimal("0.05"), max_digits=5),
                ),
                (
                    "trip_fee",
                    models.DecimalField(decimal_places=2, default=Decimal("45.00"), max_digits=8),
                ),
                (
                    "disposal_fee",
                    models.DecimalField(decimal_places=2, default=Decimal("50.00"), max_digits=8),
                ),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rate_card",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "rate cards",
            },
        ),
    ]
