# Generated by Django 6.1 on 2026-08-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_invoice_ratecard"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_reminded_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
