# Generated by Django 6.1 on 2026-08-23 06:49

import core.media_models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_customer_email_customer_last_reminded_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="filter_action",
            field=models.CharField(
                choices=[
                    ("none", "No filter / not serviced"),
                    ("cleaned", "Filter cleaned"),
                    ("replaced", "Filter replaced"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="JobAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file", models.FileField(upload_to=core.media_models._upload_path)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.job",
                    ),
                ),
            ],
            options={
                "ordering": ("pk",),
            },
        ),
    ]
