# Generated by Django 6.1 on 2026-08-23 07:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_job_filter_action_jobattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="driver",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
