# Generated by Django 6.1 on 2026-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_job_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="sms_opt_out",
            field=models.BooleanField(default=False),
        ),
    ]
