# Generated by Django 6.1 on 2026-08-23 19:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_funnelevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="plan",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription_id",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="organization",
            name="subscription_status",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="organization",
            name="trial_ends_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
