# Generated by Django 6.1 on 2026-08-23 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_organization_plan_organization_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("source", models.CharField(default="title5_kit", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
    ]
